name: Build and deploy static site to Azure Web App - scrollmotion-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0778B9AE6B94624AFB3FD184E1FE20B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B92CD017CED4CC793CAA44C544EFD5F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_313D75EBBCB641C78B02636E386087FE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'scrollmotion-app'
          slot-name: 'production'
          package: './'  # Deploy the entire project folder (static HTML, CSS, JS files)
